name: update flake inputs

on:
  schedule:
    - cron: "0 0 * * 6"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: DeterminateSystems/update-flake-lock@v20
        with:
          commit-msg: "deps(flake): update inputs"
          pr-title: "deps(flake): update inputs"
